### ISSUE TITLE
Severity Override needs to be used if entered

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openstig-web#16]
- If severity override is used, use that in display and in the charts / graphs / reports
- Identify why used and what it went to

**Comment by Cingulara** [comment]
![image](https://user-images.githubusercontent.com/46137145/53033684-993ce680-343f-11e9-8503-cc696c9a0f3d.png)

Include the CCI listing for lookup from here: http://iasecontent.disa.mil/stigs/zip/u_cci_list.zip

**Comment by DaleBingham** [comment]
DISA is removing this feature.
