### ISSUE TITLE
Information should be pulled from the uploaded checklist

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openstig-web#31]
Most of this information should be able to be pulled from the uploaded checklist.

![image](https://user-images.githubusercontent.com/41908967/55352623-49662c00-548f-11e9-98c9-599c131de07a.png)

**Comment by DaleBingham** [comment]
We can parse the checklist and pull out the info. The title we need to generate and need a rule or structure for that.

**Comment by Cingulara** [comment]
1. specify the overall system 
2. checklist has the hostname, and the type automatically read in

MY-SYSTEM:MY-HOSTNAME:MY-CHECKLIST-TYPE

@degthat8412 this is the generated title

**Comment by Cingulara** [comment]
The TARGET_KEY field will have to be matched by ID to a list of allowable types, and anything not matching is OTHER. 

We need to build the key of these based on the ID of every single effing checklist and match to it when we read them in and set a key for that in the Artifact record. :(

**Comment by Cingulara** [comment]
reading the text in the upload now, in a loop, testing that the file(s) can be parsed and the titles generated.

Added hostname, release info, and title along with system as artifact records. Will put together for the title but use independently as well.

**Comment by Cingulara** [comment]
testing this now.

**Comment by Cingulara** [comment]
GTG on this one
