### ISSUE TITLE
Exporting checklist information to Excel

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openstig-web#33]
Need to be able to export this list to Excel.

![image](https://user-images.githubusercontent.com/41908967/55355079-5a19a080-5495-11e9-99ff-915a347cdcd5.png)

**Comment by Cingulara** [comment]
Similar to #34 when you export, export  a "child row" to show the number of items per status PER CATEGORY 1, 2, 3.

**Comment by Cingulara** [comment]
for each main row, have a row for each category underneath for the came status type column to break it down

CAT 1
CAT 2
CAT 3

**Comment by Cingulara** [comment]
Getting closer.  I need to format center (excel stylesheet info in the code) and make sure CAT 1/2/3 are right justified (again excel stylesheet in the code) but pretty close. 

![image](https://user-images.githubusercontent.com/46137145/55799428-60180e80-5a9f-11e9-9600-bda51004318a.png)
