### ISSUE TITLE
Viewing Findings by CAT on Checklist Listing main screen

### ISSUE THREAD

**Issue by degthat8412** [Cingulara/openstig-web#34]
Need to be able to view findings by CAT as well.

**Comment by Cingulara** [comment]
On the checklist page, have a "child row" to show the number of items per status PER CATEGORY 1, 2, 3.

**Comment by Cingulara** [comment]
Also similar to #36 as we already call and get this information.

**Comment by Cingulara** [comment]
When we get the #16 severity override to show that instead of the status this will be complete.
