### ISSUE TITLE
Generating the Compliance listing does not clear the table if done more than once

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openstig-web#54]
When you click the "generate" button on the compliance listing, it adds to the table there already. If you run it again, it doubles up the info. We need it to do a table.clear() or whatever the databaseJS function is to clear it, and then redo the adding of rows and such. 

This needs to happen before 0.6 is finalized

**Comment by Cingulara** [comment]
added the line below in the JS that makes the compliance table.

     table.clear();
