### ISSUE TITLE
On upload, when you select multiple files at a time the upload does not work right

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openstig-web#55]
If you use the upload, but select one file at a time it works great...

if you use the upload and select more than 1 at a time (the "multiple" is in the HTML) it errors on uploading. Need to see why.

Worst case, select 1 file at a time for now. But still upload a max of 5.

**Comment by Cingulara** [comment]
fixed. I was ASS-u-ming 1 file per but I need to test that there can be up to 5 file inputs, and for each up to 5 files, or any mix of those...5 max
